# Site settings
title: Alex Longshaw
email: alexlongshaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
permalink: /:year/:title
     
url: "https://www.alexlongshaw.com"

# Build settings
markdown: kramdown
