# Site settings
title: Alex Longshaw
email: alexlongshaw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
permalink: /:year/:title
     
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alexlongshaw.com" # the base hostname & protocol for your site
twitter_username: alexlongshaw
github_username:  alexlongshaw

# Build settings
markdown: kramdown
